Increased padding to right side of .accordion-button
utsa-asc/college-dls pull request #413
Opened 2022-07-26 18:41 UTC by prd409-utsa

<img width="1663" alt="Screen Shot 2022-07-26 at 1 36 24 PM" src="https://user-images.githubusercontent.com/92815346/181086069-9b1dfd21-006d-45a8-9b15-08fb11ec99a8.png">

2022-07-26 19:25 UTC, garza-utsa requested changes

2022-07-26 19:25 UTC, garza-utsa commented on components/03-sections/01-accordion/accordion.scss
>  		position: relative;
let's also add a sane equivalent in the XS breakpoint (down at 116)
Can we add slightly less padding on mobile? =)
<img width="329" alt="Screenshot 2022-07-26 at 2 23 46 PM" src="https://user-images.githubusercontent.com/16828076/181094653-2f3aa769-99c3-47f2-8488-422492a1da14.png">

2022-07-26 19:32 UTC, lalov1 reviewed
Looks good, but I do see John's point about smaller breakpoints.

2022-07-27 14:17 UTC, garza-utsa approved these changes

2022-07-27 14:18 UTC, merged