Updating angle button hover color on colored backgrounds
utsa-asc/college-dls pull request #610
Opened 2023-08-11 16:34 UTC by jampafoo

Adding css styles for hover of angled buttons. These will match the default "Button" hover styles on blue-bg and orange-a11y-bg.

2023-08-11 17:27 UTC, garza-utsa requested changes
please adopt the same .hbs view layout as components/01-visual-styling/02-button/02-button/button.hbs, this way all background color variants can be seen and tested.

2023-08-11 18:09 UTC, garza-utsa commented
updating test page should be:
https://utsa-asc.github.io/college-dls/608-angle-button-hover-color-on-colored-backgrounds/components/detail/angled-button--large.html
after build-PR-and-deploy CI completes

2023-08-11 19:42 UTC, lalov1 reviewed
Minor change, but not required.

2023-08-11 19:42 UTC, lalov1 commented on components/01-visual-styling/02-button/03-angled-button/angled-button.hbs
Not a huge deal, but maybe put "Orange buttons on orange background." Since it's the default variant it doesn't show the color in the navigation.

2023-08-11 19:48 UTC, prd409-utsa approved these changes

2023-08-11 21:12 UTC, Uri-E approved these changes

2023-08-14 16:22 UTC, garza-utsa approved these changes
👍

2023-08-23 15:13 UTC, merged