Added directory search to DLS
utsa-asc/college-dls pull request #651
Opened 2023-11-10 17:59 UTC by lalov1

I could add more people if it looks weird with the same people.

2023-11-10 19:25 UTC, Uri-E approved these changes
Looks pretty gewd!

2023-11-12 21:15 UTC, prd409-utsa approved these changes

2023-11-13 17:21 UTC, garza-utsa commented
make sure an conform to the profile-group--compact variant:

https://utsa-asc.github.io/college-dls/components/detail/profile-group--compact.html

2023-11-13 17:32 UTC, lalov1 commented
> make sure an conform to the profile-group--compact variant:
> 
> https://utsa-asc.github.io/college-dls/components/detail/profile-group--compact.html
> 
> I think this just needs the wrapping .profile-card-list-compact inside the container

Maybe I'm confused, but I thought it would bring in the header and link if I did that.

2023-11-13 18:13 UTC, garza-utsa commented
the .profile-card-list just has override for the .row>div and .profile-card > img heights, so you should be good if you just add that class to the wrapper like the --compact.hbs does here, no need to render the entire compact element:
https://github.com/utsa-asc/college-dls/blob/main/components/03-sections/05-content-group/06-profile-group/profile-group--compact.hbs#L3

Altho, one might argue to keep it atomic, should we have a header/link less variant (of profile group) for search to use?

2023-11-14 14:10 UTC, garza-utsa requested changes
see class below on your container wrapper

2023-11-14 14:10 UTC, garza-utsa commented on components/04-reference-pages/16-faculty-directory-search/faculty-directory-search--compact.hbs
> +      <div class="container">
you should be able to add the .profile-card-list-compact here

2023-11-15 17:53 UTC, merged