Dark Mode styles for news sidebar
utsa-asc/college-dls pull request #918
Opened 2024-11-12 20:46 UTC by Uri-E

Added dark mode styles to news sidebar. Also made a small correction to timeline spacing, since I'm already here >.>

2024-11-12 21:07 UTC, prd409-utsa commented
Looks good except the border-bottom is showing after the last link on Related News.  I had used a style for :last-child in the regular/light mode to prevent that from happening. If this is being too picky for the DLS version then just disregard....but thought I would point it out. 

Otherwise, looks good!

<img width="1311" alt="Screenshot 2024-11-12 at 3 03 33 PM" src="https://github.com/user-attachments/assets/a2f38e6a-5568-4405-a57c-13c94ea67668">

2024-11-12 21:08 UTC, prd409-utsa reviewed
Looks good except the border-bottom is showing after the last link on Related News. I had used a style for :last-child in the regular/light mode to prevent that from happening. If this is being too picky for the DLS version then just disregard....but thought I would point it out.

Otherwise, looks good!

<img width="1311" alt="Screenshot 2024-11-12 at 3 03 33 PM" src="https://github.com/user-attachments/assets/8c9b4118-87a6-4df8-94c6-5531163aadc1">

2024-11-12 21:12 UTC, lalov1 reviewed
Just the item Pamela mentioned, but everything else looks good! 👍🏽

2024-11-12 21:35 UTC, garza-utsa requested changes
see @prd409-utsa 's comments on border styles :last-child

2024-11-12 21:35 UTC, garza-utsa commented on components/03-sections/02-navigation/04-side-navigation-news/side-navigation-news.scss
> +					a {
see the :last-child stuff missing from line 27 in this same file

2024-11-13 15:20 UTC, prd409-utsa approved these changes
Bottom border after third item is no longer showing. Looks good!

2024-11-13 16:37 UTC, lalov1 approved these changes
👍🏽

2024-11-13 19:52 UTC, merged